---

- name: Install the moodle via ansible
  hosts: localhost
  connection: local
  gather_facts: False
  vars: 
    mysql_root_password: admin

  tasks:

    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      
    - name: Enable UFW
      ufw: 
       direction: incoming
       policy: deny
       state: enabled

    - name: UFW allow port 22
      ufw:
       rule: allow
       port: 22
       
    - name: UFW allow port 80
      ufw:
       rule: allow
       port: 80
       
    - name: UFW allow port 3306
      ufw:
       rule: allow
       port: 3306

    - name: Install Apache2
      apt:
           name: "{{item}}"
           state: present
      with_items: 
        - apache2
        - apache2-doc
        - apache2-utils

    - name: Install Mysql Server
      apt:
        name: mysql-server
        state: present
        update_cache: yes
       
    - name: Install Mysql python module
      apt:
        name: python-mysqldb
        state: present

    - name: Start Mysql Server
      sudo: yes
      service: 
        name: mysql
        state: started
        enabled: true

    - name: Installing php
      apt: 
        name: "{{item}}" 
        state: present
      with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql

    - name: Install common PHP Extensions
      apt: 
        name: "{{item}}"
        state: present
      with_items:
        - aspell
        - graphviz
        - php7.0-curl
        - php7.0-gd
        - php7.0-intl
        - php7.0-ldap
        - php7.0-mysql
        - php7.0-pspell
        - php7.0-xml
        - php7.0-xmlrpc
        - php7.0-zip
      notify:
        - restart apache2

    - name: Download moodle
      unarchive:
        src: https://download.moodle.org/download.php/direct/stable32/moodle-latest-32.tgz
        dest: /var/www/html
        remote_src: yes

    - name: create a moodledata folder and change the ownership
      file:
        path: /var/www/moodledata
        state: directory
        owner: www-data
        group: www-data
        mode: 0777

    - name: change the permissions for /var/www/html/
      file:
        path: /var/www/html/moodle
        mode: 0777
        recurse: yes

    - name: change the mysqlDatabase configuration file
      blockinfile: 
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        block: |
          defult_storage_engine = innodb
          innodb_file_per_table = 1
          innodb_file_format = Barracuda
          
    # Add mysql user
    - mysql_user:
       name: moodler
       password: moodlerpassword
       priv: '*.*:ALL,GRANT'
       state: present

    - name: Fix permission for /usr/bin/php
      file: 
        path: /usr/bin/php
        mode: 0777
        
    - name: Fix permission for /var/www/html/moodle/admin/cli/install.php
      file: 
        path: /var/www/html/moodle/admin/cli/install.php
        mode: 0777  
    
    - name: configuration the moodle website
      shell: |
          ip=`curl ifconfig.co`

          sudo -u www-data /usr/bin/php /var/www/html/moodle/admin/cli/install.php --chmod=777 --lang=en --wwwroot=http://$ip/moodle --dataroot=/var/www/moodledata --dbtype=mysqli \ 
          --dbhost=localhost --dbname=moodle --dbuser=moodler --dbpass=moodlerpassword --dbport=22 --prefix=mdl_ --fullname=Group11-2018 --shortname=G11 --adminuser=admin --adminpass=password --non-interactive --allow-unstable --agree-license
     
          
    - name: print stdout
      debug:
        msg: ""
          
  handlers:
  - name: restart apache2
    service: 
      name: apache2
      state: restarted
